---
apiVersion: v1
kind: Namespace
metadata:
  name: envoy

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy
  namespace: envoy
  labels:
    k8s-app: envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: envoy
  template:
    metadata:
      labels:
        k8s-app: envoy
    spec:
      containers:
        - name: envoy
          image: envoyproxy/envoy
          args:
            - envoy
            - --config-path /etc/envoy/envoy.yaml
          ports:
            - name: mysql
              containerPort: 3306
            - name: envoy-admin
              containerPort: 9901
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy
      volumes:
        - name: envoy-config
          configMap:
            name: envoy-config

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: envoy-config
  namespace: envoy
  labels:
    k8s-app: envoy
data:
  envoy.yaml: |-
    static_resources:
      listeners:
      - name: mysql_listener
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 3306
        filter_chains:
        - filters:
          - name: envoy.tcp_proxy
            config:
              stat_prefix: mysql
              cluster: mysql
              idle_timeout: 60s
      clusters:
      - name: mysql
        connect_timeout: 1s
        type: strict_dns # static
        hosts:
        - socket_address:
          address: mysql.lominorama.com
            port_value: 3306
    admin:
      access_log_path: "/dev/null"
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9901

---
kind: Service
apiVersion: v1
metadata:
  name: envoy
  namespace: envoy
  labels:
    k8s-app: envoy
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    k8s-app: envoy
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
      protocol: TCP
    - name: envoy-admin
      port: 9901
      targetPort: envoy-admin
      protocol: TCP
